export { RulesPanel } from './RulesPanel.tsx'
export type { RulesPanelProps } from './RulesPanel.tsx'
export { parseRuleProfile, RuleProfileError, assertSafeRecommendation } from './schema.ts'
export { decideRule } from './decide.ts'
export { recommendRule, formatRecommendation } from './recommend.ts'
export { presentAmpel, AMPEL_LABEL_PRODUCTION, AMPEL_LABEL_PROVISIONAL, AMPEL_LABEL_UNAVAILABLE } from './display.ts'
export { RULE_PROFILES, DEFAULT_RULE_PROFILE_ID, getRuleProfile, shippedProductionProfiles } from './catalog.ts'
export { runRulesHarness } from './harness.ts'
export type { RulesHarnessResult, RulesHarnessCase } from './harness.ts'
export { evaluateProfile, RULE_PLUMBING_FIXTURES } from './evaluate.ts'
